currency:
  url: ${API_URL:https://api.apilayer.com/exchangerates_data/convert}
  api_key: ${API_KEY:bOv9VzwtvbtNuPhxLT3oZ5Xat8qE8ufB}

server:
  port: 8080

spring:
  datasource:
    type: org.postgresql.jdbc2.optional.SimpleDataSource
    username: ${USER_NAME:postgres}
    password: ${PASSWORD:mysecretpassword}
    url: ${URL:jdbc:postgresql://localhost:5432/postgres}
  config:
    import: optional:file:.env[.properties]
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: currency-converter

keycloak:
  auth-server-url: http://192.168.31.149:8081
  autodetect-bearer-only: true
  credentials:
    secret: xmfeZdBq5R9jtxbZTomrKhbwdSxAo833
  realm: software
  resource: backend
  ssl-required: none
  use-resource-role-mappings: false
  security-constraints:
    - auth-roles:
        - ADMIN
        - USER
      security-collections:
        - name: SERVICIOS DE ADMINISTRADOR
          omitted-methods:
            - OPTIONS
          patterns:
            - /api/v1/currency/list
            - /api/v1/currency/obtain

management:
  endpoints:
    web:
      exposure:
        include: "*"

